spring:
  application:
    name: leitor-webservice
  datasource:
    url: jdbc:mysql://localhost:3306/spring-bat-01
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
chunkSize: 20
maxPage: 3
pageSize: 10
